ALTER TABLE "Course"
ADD COLUMN IF NOT EXISTS "groupInternationalFeeINR" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "oneToOneInternationalFeeINR" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "joiningFeeInternationalINR" DOUBLE PRECISION;
