-- Persist the GST breakdown used by finance reports and tax invoices.
-- IF NOT EXISTS keeps this migration safe for databases that previously
-- received these columns through `prisma db push`.
ALTER TABLE "Enrollment"
  ADD COLUMN IF NOT EXISTS "taxableValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "cgst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sgst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "igst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "totalGst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gstRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "placeOfSupply" TEXT,
  ADD COLUMN IF NOT EXISTS "isGstInclusive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Payment"
  ADD COLUMN IF NOT EXISTS "taxableValue" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "cgst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sgst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "igst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "totalGst" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gstRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "placeOfSupply" TEXT,
  ADD COLUMN IF NOT EXISTS "isGstInclusive" BOOLEAN NOT NULL DEFAULT true;
