ALTER TABLE "PendingUpgrade"
ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';

ALTER TABLE "PendingUpgrade"
ADD COLUMN IF NOT EXISTS "expectedAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
